apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-private-repo
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/ganislp/integrationSendMessages.git
  username: ganislp@gmail.com
  password: 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